# JavaScript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    docker:
    - image: cypress/base:14.15.0

    environment:
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}

    - run: yarn install --frozen-lockfile
    - run: yarn cypress verify

    - save_cache:
        key: v1-dependencies-{{ checksum "yarn.lock" }}
        paths:
        - ./node_modules
        - ~/.cache

    - run:
        name: Lerna prepare ğŸ²
        command: yarn lerna:prepare

    - run:
        name: Unit tests â“
        command: yarn test
        no_output_timeout: 10m

    - run:
        name: Cypress e2e tests ğŸ§ª
        command: yarn test:e2e:record
        no_output_timeout: 10m